import { useState } from 'react'
import Head from 'next/head'
import styles from '../styles/contact.module.css'

const Contact = () => {
	const [name, setName] = useState('')
	const [email, setEmail] = useState('')
	const [subject, setSubject] = useState('')
	const [message, setMessage] = useState('')

	const handleSubmit = async (e) => {
		e.preventDefault()
		const requestBody = {
			name,
			email,
			subject,
			message,
		}
		const response = await fetch('/api/contact', {
			method: 'POST',
			body: JSON.stringify(requestBody),
		})
		const { error } = await response.json()
		if (error) {
			console.log(error)
			return
		}
	}

	return (
		<>
			<Head>
				<title>Contact Me</title>
				{/* <meta name='description' content='Generated by create next app' /> */}
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={styles.main}>
				<h1>Getting in touch is easy!</h1>
				<form onSubmit={handleSubmit} className={styles.form}>
					<label htmlFor='name'>Name:</label>
					<input
						id='name'
						type='text'
						onChange={(e) => setName(e.target.value)}
					/>
					<label htmlFor='email'>Email:</label>
					<input
						id='email'
						type='email'
						onChange={(e) => setEmail(e.target.value)}
					/>
					<label htmlFor='subject'>Subject:</label>
					<input
						id='subject'
						type='text'
						onChange={(e) => setSubject(e.target.value)}
					/>
					<label htmlFor='message'>Message:</label>
					<textarea
						id='message'
						type='text'
						rows='4'
						onChange={(e) => setMessage(e.target.value)}
					/>
					<button type='submit'>Send</button>
				</form>
			</main>
		</>
	)
}

export default Contact
